#### Python Pandas Project - 4
Case Study on Uber Cab's Data

In [1]:
## Importing libraries
import pandas as pd
import numpy as np

ImportError: Unable to import required dependencies:
numpy: No module named 'numpy'

In [3]:
#### Reading the Data
df = pd.read_csv(r"C:\Users\manoj.c\Documents\PANDAS_PROJECT\Pandas-Project-4\Datasets\My Uber Drives.csv")
df.head()

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit

In [4]:
## Get n first rows
n = 7 
df.head(n)

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
5,1/6/2016 17:15,1/6/2016 17:19,Business,West Palm Beach,West Palm Beach,4.3,Meal/Entertain
6,1/6/2016 17:30,1/6/2016 17:35,Business,West Palm Beach,Palm Beach,7.1,Meeting

In [5]:
## To get last rows
df.tail()

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [6]:
## To get rows & columns
df.shape

(1156, 7)

In [7]:
print(f"There are {df.shape[0]} rows and {df.shape[1]} columns in the dataset")

There are 1156 rows and 7 columns in the dataset

In [8]:
## To get total number of elements
df.size

8092

In [9]:
df.shape[0] * df.shape[1]

8092

In [10]:
## To get the total number of null values accross the columns
df.isnull().sum()

START_DATE*      0
END_DATE*        1
CATEGORY*        1
START*           1
STOP*            1
MILES*           0
PURPOSE*       503
dtype: int64

In [11]:
df.isna().sum()

START_DATE*      0
END_DATE*        1
CATEGORY*        1
START*           1
STOP*            1
MILES*           0
PURPOSE*       503
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   START_DATE*  1156 non-null   object
 1   END_DATE*    1155 non-null   object
 2   CATEGORY*    1155 non-null   object
 3   START*       1155 non-null   object
 4   STOP*        1155 non-null   object
 5   MILES*       1156 non-null   float64
 6   PURPOSE*     653 non-null    object
dtypes: float64(1), object(6)
memory usage: 63.3+ KB

In [13]:
df.count()

START_DATE*    1156
END_DATE*      1155
CATEGORY*      1155
START*         1155
STOP*          1155
MILES*         1156
PURPOSE*        653
dtype: int64

In [14]:
## to get the entires having NULL values in purpose columns
df.columns

Index(['START_DATE*', 'END_DATE*', 'CATEGORY*', 'START*', 'STOP*', 'MILES*',
       'PURPOSE*'],
      dtype='object')

In [15]:
df['PURPOSE*'].isnull().sum()

np.int64(503)

In [16]:
df[df['PURPOSE*'].isnull()]

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
32,1/19/2016 9:09,1/19/2016 9:23,Business,Whitebridge,Lake Wellingborough,7.2,NaN
85,2/9/2016 10:54,2/9/2016 11:07,Personal,Whitebridge,Northwoods,5.3,NaN
86,2/9/2016 11:43,2/9/2016 11:50,Personal,Northwoods,Tanglewood,3.0,NaN
87,2/9/2016 13:36,2/9/2016 13:52,Personal,Tanglewood,Preston,5.1,NaN
...,...,...,...,...,...,...,...
1066,12/19/2016 14:37,12/19/2016 14:50,Business,Unknown Location,Unknown Location,5.4,NaN
1069,12/19/2016 19:05,12/19/2016 19:17,Business,Islamabad,Unknown Location,2.2,NaN
1071,12/20/2016 8:49,12/20/2016 9:24,Business,Unknown Location,Rawalpindi,12.0,NaN
1143,12/29/2016 20:53,12/29/2016 21:42,Business,Kar?chi,Unknown Location,6.4,NaN
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [17]:
## to get the entires having Non NULL values in purpose columns
df[~df['PURPOSE*'].isnull()]

,START_DATE*,END_DATE*,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit
5,1/6/2016 17:15,1/6/2016 17:19,Business,West Palm Beach,West Palm Beach,4.3,Meal/Entertain
...,...,...,...,...,...,...,...
1150,12/31/2016 1:07,12/31/2016 1:14,Business,Kar?chi,Kar?chi,0.7,Meeting
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site

In [18]:
## Remove the * from columns
df.columns

Index(['START_DATE*', 'END_DATE*', 'CATEGORY*', 'START*', 'STOP*', 'MILES*',
       'PURPOSE*'],
      dtype='object')

In [19]:
df.rename(columns={"START_DATE*": 'START_DATE', 'END_DATE*':'END_DATE'}, inplace=True)

In [20]:
## Here without inplace=True the columns would not have changed their names
df.columns

Index(['START_DATE', 'END_DATE', 'CATEGORY*', 'START*', 'STOP*', 'MILES*',
       'PURPOSE*'],
      dtype='object')

In [21]:
df.columns.str.replace("*","")

Index(['START_DATE', 'END_DATE', 'CATEGORY', 'START', 'STOP', 'MILES',
       'PURPOSE'],
      dtype='object')

In [25]:
## replacing the column names with lamda function
df.rename(mapper= lambda x: x.replace("*"," "),axis=1).head(3)

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies

In [ ]:
df.head()

,START_DATE,END_DATE,CATEGORY*,START*,STOP*,MILES*,PURPOSE*
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit

In [32]:
## Get the entries in the data where the START location is 'Fort Pierce'
df[df['START '] == 'Fort Pierce']

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting
4,1/6/2016 14:42,1/6/2016 15:49,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit

In [ ]:
## Get the entries in the data where the STOP location is 'Fort Pierce'
df[df['STOP '] == 'Fort Pierce']

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE
0,1/1/2016 21:11,1/1/2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,1/2/2016 1:25,1/2/2016 1:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,1/2/2016 20:25,1/2/2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies
3,1/5/2016 17:31,1/5/2016 17:45,Business,Fort Pierce,Fort Pierce,4.7,Meeting

In [43]:
## Sort the entries in the data in ascending order of the 'MILES' column
df_sorted = df.sort_values(by='MILES ', ascending=True)
df_sorted.head(10)

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE
120,2/17/2016 16:38,2/17/2016 16:43,Business,Katunayaka,Katunayaka,0.5,Errand/Supplies
420,6/8/2016 17:16,6/8/2016 17:18,Business,Soho,Tribeca,0.5,Errand/Supplies
44,1/26/2016 17:27,1/26/2016 17:29,Business,Cary,Cary,0.5,Errand/Supplies
516,7/5/2016 16:48,7/5/2016 16:52,Business,Whitebridge,Whitebridge,0.6,Errand/Supplies
1111,12/25/2016 0:10,12/25/2016 0:14,Business,Lahore,Lahore,0.6,Errand/Supplies
1121,12/27/2016 12:53,12/27/2016 12:57,Business,Kar?chi,Kar?chi,0.6,Meal/Entertain
1110,12/24/2016 22:04,12/24/2016 22:09,Business,Lahore,Lahore,0.6,Errand/Supplies
945,11/12/2016 13:46,11/12/2016 13:50,Business,Central,West Berkeley,0.6,NaN
292,4/1/2016 16:52,4/1/2016 16:57,Personal,Kissimmee,Kissimmee,0.7,NaN
807,10/13/2016 13:02,10/13/2016 13:02,Business,Islamabad,Islamabad,0.7,NaN

In [41]:
df.columns

Index(['START_DATE', 'END_DATE', 'CATEGORY ', 'START ', 'STOP ', 'MILES ',
       'PURPOSE '],
      dtype='object')

In [48]:
## Drop all the columns where there NULL values in the STOP Column
# firstly find out how many NULL are there
df.isnull().sum()

START_DATE      0
END_DATE        1
CATEGORY        1
START           1
STOP            1
MILES           0
PURPOSE       503
dtype: int64

In [50]:
# there is 1 value in STOP , lets find that then drop it
df[df['STOP '].isnull()]

     START_DATE END_DATE CATEGORY  START  STOP    MILES  PURPOSE
1155     Totals      NaN       NaN    NaN   NaN  12204.7      NaN

In [51]:
# we found lets drop it 
df = df.dropna(subset='STOP ')

In [52]:
# lets verify using above statement once
df[df['STOP '].isnull()]

Empty DataFrame
Columns: [START_DATE, END_DATE, CATEGORY , START , STOP , MILES , PURPOSE ]
Index: []

In [53]:
## Use describe() function to get the statistical properties about the numerical columns in the data.
df.describe()

            MILES
count  1155.000000
mean     10.566840
std      21.579106
min       0.500000
25%       2.900000
50%       6.000000
75%      10.400000
max     310.300000

In [61]:
## Understanding the START and STOP points.
print(df['START '].unique())

['Fort Pierce' 'West Palm Beach' 'Cary' 'Jamaica' 'New York' 'Elmhurst'
 'Midtown' 'East Harlem' 'Flatiron District' 'Midtown East'
 'Hudson Square' 'Lower Manhattan' "Hell's Kitchen" 'Downtown' 'Gulfton'
 'Houston' 'Eagan Park' 'Morrisville' 'Durham' 'Farmington Woods'
 'Whitebridge' 'Lake Wellingborough' 'Fayetteville Street' 'Raleigh'
 'Hazelwood' 'Fairmont' 'Meredith Townes' 'Apex' 'Chapel Hill'
 'Northwoods' 'Edgehill Farms' 'Tanglewood' 'Preston' 'Eastgate'
 'East Elmhurst' 'Jackson Heights' 'Long Island City' 'Katunayaka'
 'Unknown Location' 'Colombo' 'Nugegoda' 'Islamabad' 'R?walpindi'
 'Noorpur Shahan' 'Heritage Pines' 'Westpark Place' 'Waverly Place'
 'Wayne Ridge' 'Weston' 'East Austin' 'West University' 'South Congress'
 'The Drag' 'Congress Ave District' 'Red River District' 'Georgian Acres'
 'North Austin' 'Coxville' 'Convention Center District' 'Austin' 'Katy'
 'Sharpstown' 'Sugar Land' 'Galveston' 'Port Bolivar' 'Washington Avenue'
 'Briar Meadow' 'Latta' 'Jacksonville' 'Couples Glen' 'Kissimmee'
 'Lake Reams' 'Orlando' 'Sand Lake Commons' 'Sky Lake' 'Daytona Beach'
 'Ridgeland' 'Florence' 'Meredith' 'Holly Springs' 'Chessington'
 'Burtrose' 'Parkway' 'Mcvan' 'Capitol One' 'University District'
 'Seattle' 'Redmond' 'Bellevue' 'San Francisco' 'Palo Alto' 'Sunnyvale'
 'Newark' 'Menlo Park' 'Old City' 'Savon Height' 'Kilarney Woods'
 'Townes at Everett Crossing' 'Huntington Woods' 'Seaport'
 'Medical Centre' 'Rose Hill' 'Soho' 'Tribeca' 'Financial District'
 'Oakland' 'Emeryville' 'Berkeley' 'Kenner' 'CBD' 'Lower Garden District'
 'Lakeview' 'Storyville' 'New Orleans' 'Metairie' 'Chalmette' 'Arabi'
 'Pontchartrain Shores' 'Marigny' 'Covington' 'Mandeville'
 'Jamestown Court' 'Summerwinds' 'Parkwood' 'Pontchartrain Beach'
 'St Thomas' 'Banner Elk' 'Elk Park' 'Newland' 'Boone' 'Stonewater'
 'Lexington Park at Amberly' 'Arlington Park at Amberly' 'Arlington'
 'Kalorama Triangle' 'K Street' 'West End' 'Connecticut Avenue'
 'Columbia Heights' 'Washington' 'Wake Forest' 'Lahore' 'Karachi'
 'SOMISSPO' 'West Berkeley' 'North Berkeley Hills' 'San Jose' 'Eagle Rock'
 'Winston Salem' 'Asheville' 'Topton' 'Hayesville' 'Bryson City' 'Almond'
 'Mebane' 'Agnew' 'Cory' 'Renaissance' 'Santa Clara' 'NOMA' 'Sunnyside'
 'Ingleside' 'Central' 'Tenderloin' 'College Avenue' 'South' 'Southside'
 'South Berkeley' 'Mountain View' 'El Cerrito' 'Krendle Woods' 'Wake Co.'
 'Fuquay-Varina' 'Rawalpindi' 'Kar?chi' 'Katunayake' 'Gampaha']

In [64]:
len(df['START '].unique())

177

In [65]:
print(df['STOP '].unique())

['Fort Pierce' 'West Palm Beach' 'Palm Beach' 'Cary' 'Morrisville'
 'New York' 'Queens' 'East Harlem' 'NoMad' 'Midtown' 'Midtown East'
 'Hudson Square' 'Lower Manhattan' "Hell's Kitchen" 'Queens County'
 'Gulfton' 'Downtown' 'Houston' 'Jamestown Court' 'Durham' 'Whitebridge'
 'Lake Wellingborough' 'Raleigh' 'Umstead' 'Hazelwood' 'Westpark Place'
 'Meredith Townes' 'Leesville Hollow' 'Apex' 'Chapel Hill'
 'Williamsburg Manor' 'Macgregor Downs' 'Edgehill Farms' 'Northwoods'
 'Tanglewood' 'Preston' 'Walnut Terrace' 'Jackson Heights' 'East Elmhurst'
 'Midtown West' 'Long Island City' 'Jamaica' 'Unknown Location' 'Colombo'
 'Nugegoda' 'Katunayaka' 'Islamabad' 'R?walpindi' 'Noorpur Shahan'
 'Heritage Pines' 'Waverly Place' 'Wayne Ridge' 'Depot Historic District'
 'Weston' 'West University' 'South Congress' 'Arts District'
 'Congress Ave District' 'Red River District' 'The Drag'
 'Convention Center District' 'North Austin' 'Coxville' 'Katy' 'Alief'
 'Sharpstown' 'Sugar Land' 'Galveston' 'Port Bolivar' 'Washington Avenue'
 'Briar Meadow' 'Greater Greenspoint' 'Latta' 'Jacksonville' 'Kissimmee'
 'Isles of Buena Vista' 'Orlando' 'Lake Reams' 'Vista East' 'Sky Lake'
 'Sand Lake Commons' 'Daytona Beach' 'Ridgeland' 'Florence' 'Cedar Hill'
 'Holly Springs' 'Harden Place' 'Chessington' 'Burtrose' 'Parkway'
 'Capitol One' 'University District' 'Redmond' 'Bellevue' 'Seattle'
 'Mcvan' 'Palo Alto' 'Sunnyvale' 'Newark' 'Menlo Park' 'San Francisco'
 'Parkway Museums' 'Hog Island' 'Savon Height' 'Kildaire Farms'
 'Kilarney Woods' 'Gramercy-Flatiron' 'Tudor City' 'Soho' 'Tribeca'
 'Financial District' 'Kips Bay' 'Emeryville' 'Berkeley' 'Oakland'
 'Bay Farm Island' 'New Orleans' 'Lower Garden District' 'Lakeview'
 'Storyville' 'Faubourg Marigny' 'Metairie' 'Kenner' 'Bywater' 'Chalmette'
 'Arabi' 'Pontchartrain Shores' 'Marigny' 'Covington' 'Mandeville'
 'Summerwinds' 'Parkwood' 'Pontchartrain Beach' 'CBD' 'St Thomas'
 'Banner Elk' 'Elk Park' 'Newland' 'Boone' 'Stonewater'
 'Lexington Park at Amberly' 'Arlington Park at Amberly' 'Washington'
 'K Street' 'Kalorama Triangle' 'Northwest Rectangle' 'Columbia Heights'
 'Arlington' 'Farmington Woods' 'Wake Forest' 'Lahore' 'Karachi'
 'French Quarter' 'North Berkeley Hills' 'Southside' 'San Jose'
 'Eagle Rock' 'Huntington Woods' 'Winston Salem' 'Asheville' 'Topton'
 'Hayesville' 'Bryson City' 'Almond' 'Mebane' 'Santa Clara' 'Cory' 'Agnew'
 'Renaissance' 'West Berkeley' 'Central' 'Sunnyside' 'Ingleside'
 'Potrero Flats' 'SOMISSPO' 'Tenderloin' 'College Avenue' 'South'
 'Southwest Berkeley' 'South Berkeley' 'Mountain View' 'El Cerrito'
 'Wake Co.' 'Fuquay-Varina' 'Rawalpindi' 'Kar?chi' 'Gampaha' 'Ilukwatta']

In [66]:
len(df['STOP '].unique())

188

In [67]:
## Use value_counts() function to demonstrate the proportion of different categorical values in the data
df['START '].value_counts().head(10)

START
Cary                201
Unknown Location    148
Morrisville          85
Whitebridge          68
Islamabad            57
Durham               37
Lahore               36
Raleigh              28
Kar?chi              27
Westpark Place       17
Name: count, dtype: int64

In [68]:
df['STOP '].value_counts().head(10)

STOP
Cary                203
Unknown Location    149
Morrisville          84
Whitebridge          65
Islamabad            58
Durham               36
Lahore               36
Raleigh              29
Kar?chi              26
Apex                 17
Name: count, dtype: int64

In [74]:
## Get the number of rides where START & STOP locations are the same
len(df[df['START '] == df['STOP ']][['START ','STOP ']])

288

In [85]:
## Find the favorite starting point according to the total number of MILES covered.
df.groupby('START ')['MILES '].sum().sort_values(ascending=False).head(10)

START
Unknown Location    1976.5
Cary                1791.3
Morrisville          671.7
Raleigh              433.0
Islamabad            401.2
Durham               384.4
Jacksonville         375.2
Latta                310.3
Asheville            287.7
Whitebridge          273.4
Name: MILES , dtype: float64

In [ ]:
## Find the starting point for the ride where maximum miles are covered.
df.loc[df['MILES '].idxmax(),['START ','MILES ']]

# or

df[df['MILES '] == max(df['MILES '])][['START ', 'MILES ']]

    START   MILES
269  Latta   310.3

In [100]:
## Check the data types of all columns in dataset
df.dtypes

START_DATE     object
END_DATE       object
CATEGORY       object
START          object
STOP           object
MILES         float64
PURPOSE        object
dtype: object

In [109]:
## Drop the 'Unknown Location' value from START & STOP column
df1 = df[(df['START '] != 'Unknown Location') & (df['STOP '] != 'Unknown Location')]

In [118]:
pd.concat([
    df1['START '].value_counts().rename('START'),
    df1['STOP '].value_counts().rename('STOP')
], axis=1).head(10)

                START   STOP
Cary            200.0  203.0
Morrisville      85.0   83.0
Whitebridge      68.0   65.0
Durham           37.0   36.0
Islamabad        29.0   30.0
Raleigh          28.0   29.0
Lahore           27.0   27.0
Kar?chi          20.0   20.0
Apex             17.0   17.0
Westpark Place   17.0   16.0

In [127]:
## Find the most popular START-STOP pair according to the total number of rides covered.
df1.groupby(['START ','STOP ']).size().sort_values(ascending=False).reset_index(name="Count").head(10)

        START         STOP   Count
0  Morrisville         Cary     75
1         Cary  Morrisville     67
2         Cary         Cary     53
3         Cary       Durham     36
4       Durham         Cary     32
5       Lahore       Lahore     27
6    Islamabad    Islamabad     25
7         Cary      Raleigh     23
8      Raleigh         Cary     21
9      Kar?chi      Kar?chi     20

In [139]:
## Convert the datatypes of START_DATE and END_DATE columns to datetime
df['START_DATE'] = pd.to_datetime(df['START_DATE'])
df["END_DATE"] = pd.to_datetime(df["END_DATE"])
df.dtypes

START_DATE    datetime64[ns]
END_DATE      datetime64[ns]
CATEGORY              object
START                 object
STOP                  object
MILES                float64
PURPOSE               object
dtype: object

In [153]:
## Extract the month from START_DATE and try to get the proportion of rides of different months.
df['MONTH'] = df['START_DATE'].dt.month
df['MONTH_NAME'] = df['START_DATE'].dt.month_name()
df.head()

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE,MONTH,MONTH_NAME
0,2016-01-01 21:11:00,2016-01-01 21:17:00,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain,1,January
1,2016-01-02 01:25:00,2016-01-02 01:37:00,Business,Fort Pierce,Fort Pierce,5.0,NaN,1,January
2,2016-01-02 20:25:00,2016-01-02 20:38:00,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies,1,January
3,2016-01-05 17:31:00,2016-01-05 17:45:00,Business,Fort Pierce,Fort Pierce,4.7,Meeting,1,January
4,2016-01-06 14:42:00,2016-01-06 15:49:00,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit,1,January

In [145]:
df.groupby("MONTH")['MILES '].sum()

MONTH
1      512.9
2      908.2
3     1693.9
4     1113.0
5      363.8
6      842.8
7     1224.6
8     1335.5
9      601.8
10    1810.0
11     816.9
12     981.3
Name: MILES , dtype: float64

In [159]:
ride_counts = df[['MONTH','MONTH_NAME']].value_counts().sort_index()
print(ride_counts)

MONTH  MONTH_NAME
1      January        61
2      February      115
3      March         113
4      April          54
5      May            49
6      June          108
7      July          112
8      August        133
9      September      36
10     October       106
11     November      122
12     December      146
Name: count, dtype: int64

In [161]:
proportion = (ride_counts/ride_counts.sum()) * 100
proportion = proportion.round(2)
print(proportion)

MONTH  MONTH_NAME
1      January        5.28
2      February       9.96
3      March          9.78
4      April          4.68
5      May            4.24
6      June           9.35
7      July           9.70
8      August        11.52
9      September      3.12
10     October        9.18
11     November      10.56
12     December      12.64
Name: count, dtype: float64

In [168]:
## Find the average distance covered each month
avg_dist = df.groupby(["MONTH","MONTH_NAME"])['MILES '].mean()
avg_dist = avg_dist.round(2)
print(avg_dist)

MONTH  MONTH_NAME
1      January        8.41
2      February       7.90
3      March         14.99
4      April         20.61
5      May            7.42
6      June           7.80
7      July          10.93
8      August        10.04
9      September     16.72
10     October       17.08
11     November       6.70
12     December       6.72
Name: MILES , dtype: float64

In [172]:
## Extract the day from the START_DATE column
df["DAY"] = df['START_DATE'].dt.day
df.head()

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE,MONTH,MONTH_NAME,DAY
0,2016-01-01 21:11:00,2016-01-01 21:17:00,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain,1,January,1
1,2016-01-02 01:25:00,2016-01-02 01:37:00,Business,Fort Pierce,Fort Pierce,5.0,NaN,1,January,2
2,2016-01-02 20:25:00,2016-01-02 20:38:00,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies,1,January,2
3,2016-01-05 17:31:00,2016-01-05 17:45:00,Business,Fort Pierce,Fort Pierce,4.7,Meeting,1,January,5
4,2016-01-06 14:42:00,2016-01-06 15:49:00,Business,Fort Pierce,West Palm Beach,63.7,Customer Visit,1,January,6

In [177]:
## Find the total miles covered per category per purpose
df.groupby(["CATEGORY ","PURPOSE "]).sum(numeric_only=True)["MILES "].sort_values(ascending=False).reset_index(name="TOTAL_MILES")

  CATEGORY          PURPOSE   TOTAL_MILES
0  Business          Meeting       2851.3
1  Business   Customer Visit       2089.5
2  Business   Meal/Entertain        911.7
3  Business   Temporary Site        523.7
4  Business  Errand/Supplies        508.0
5  Business  Between Offices        197.0
6  Personal          Commute        180.2
7  Personal           Moving         18.2
8  Business   Airport/Travel         16.5
9  Personal      Charity ($)         15.1